### ISSUE TITLE
Checking backtrader with sptrader

### ISSUE THREAD

**Issue by junajo10** [joequant/sptrader#7] opened 2016-09-30 14:55 UTC
I get this error:

C:\Users\jj\AppData\Local\Continuum\Anaconda\envs\python35\lib\site-package
s\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has n
o effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
C:\Users\jj\AppData\Local\Continuum\Anaconda\envs\python35\lib\site-package
s\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has n
o effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
 * Debugger is active!
 * Debugger pin code: 204-259-178
127.0.0.1 - - [30/Sep/2016 16:47:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Sep/2016 16:47:16] "GET /static/ag-grid.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Sep/2016 16:47:16] "GET /static/theme-bootstrap.css HTTP/1.1"
200 -
127.0.0.1 - - [30/Sep/2016 16:47:16] "GET /static/sptrader.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Sep/2016 16:47:16] "GET /static/bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:47:18] "GET /static/bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:47:18] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:47:18] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:47:36] "GET /static/bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:47:36] "GET /static/bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:50:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Sep/2016 16:50:18] "GET /static/ag-grid.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Sep/2016 16:50:18] "GET /static/theme-bootstrap.css HTTP/1.1"
200 -
127.0.0.1 - - [30/Sep/2016 16:50:18] "GET /static/bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [30/Sep/2016 16:50:18] "GET /static/sptrader.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Sep/2016 16:50:19] "GET /favicon.ico HTTP/1.1" 404 -

Later i set http://localhost:5000/, but the screen is empty....

**Comment by joequant** [comment] 2016-10-01 21:43
The error is normal.

The problem is that the source package doesn't some of the generated nodejs files.  I added some very basic build instructions in INSTALL.md

If you have some coding experience, let me know, since we can improve the install process.

**Comment by junajo10** [comment] 2016-10-02 06:58
I have experience as programmer, and i have reviewed INSTALL file, i have reinstalled all components, but the problem continues. could you suggest any thing i could check?

Thanks a lot

**Comment by joequant** [comment] 2016-10-02 12:38
Run the system under firefox-dev and look at the console log.  The system
puts a lot of output into the console.log so you should be able to see why
the system is not rendering.

Also check if static/bundle.js is there and it should be about 6 megabytes.

**Comment by junajo10** [comment] 2016-10-02 20:17
I  don't have any file bundle.js in the static folder
I am running the code, calling python webui.py 
GET 
http://localhost:5000/static/bundle.js

**Comment by joequant** [comment] 2016-10-02 21:14
Run the commands

npm install
npm run build-js

This should generate a file static/bundle.js

**Comment by joequant** [comment] 2016-10-02 21:18
Also out of curiosity what platform are you running on.  This should work
with both windows and linux, although the issues are with install scripts.

**Comment by junajo10** [comment] 2016-10-02 21:57
Hi,

Windows
 i have just created the file bundle.js.
Now the login screen is showed, i don´t know if i could create a demo account (DEMO201608054) or i could use backtesting without login?

Thanks a lot

**Comment by joequant** [comment] 2016-10-02 23:55
Hi.

You can get your own demo account from this link

http://www.sharppoint.com.hk/algo.php?lang=1&mod=api

They have preexisting demo accounts, or you can request your own account
from SP customer support.

Backtesting should not require a demo account, but the UI forces you to log
in to do backtesting.  Would be delighted if this restriction were
removed.  This would be purely an issue with changing the UI.

This system is being used by a client to do algo strategies so for the next
few weeks, I'll be focused on getting things into production for them, but
I'd be delighted to pull in any fixes or changes you may have.

**Comment by junajo10** [comment] 2016-10-03 07:09
Thanks again, ia am trying to connect but i am not able to get it. My parameters are:

Login
Host
localHhost
Port
5000
License
DLLAPITEST
App Id
DLLAPITEST
User Id
SPAPI14
Password
12345678

**Comment by joequant** [comment] 2016-10-03 08:33
The server should be demo.spsystem.info and the port is 8080

It turns out that the demo accounts on the page are often used, and I've
found that I've had to request a demo account from sp customer service.

**Comment by junajo10** [comment] 2016-10-06 14:42
thanks a lot, now it is working,

**Comment by joequant** [comment] 2016-10-12 01:31
Closing issue.

**Closed by joequant** 2016-10-12 01:31 UTC
